# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/profiles/qemu-guest.nix>
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "ehci_pci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/77072b6f-b73e-4ebd-be6d-b1aae19a8c06";
      fstype = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B83B-DEFC";
      fstype = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/cfd706f7-2604-4ed4-ac10-6babaf1c44e3"; }
    ];

  nix.maxJobs = lib.mkDefault 2;
}
